test/isNotNil.ts, types/isNotNil.d.ts
isNotNil, new for 0.29.0, was already defined in the `ramda@ts` branch and was migrated over with it. This update adds type narrowing
eg
```
const maybeNumber = (): number | null => {
if (Math.random() > 0.5) {
return null;
}
return 123;
};
const r = maybeNumber();
//    ^? number | null 
if (isNotNil(r)) {
r
//^? number
}
```
=> Update: `isNotNil` return NoNullable

test/forEach.test.ts, types/forEach.d.ts
2 changes, these should be backward compatible
First is adding a generic `U` for the type of `list`. `forEach` passes through the incoming `list`. The previous version did this:
```typescript
const readonlyArr: readonly number[]; = [/*...*/];
const next = forEach(console.log, readonlyArr);
//    ^? number[], NOT readonly number[]
```
By using `<U extends readonly T[]>` and returning `U`, the `readonly number[]` is preserved
Second is adding the `(__: Placeholder, list: U)` variety
=> Update: forEach

types/pathEq.d.ts
=> Fix: `pathEq` Argument order change for 0.29.0 release

test/defaultTo.test.ts, types/defaultTo.d.ts, types/util/tools.d.ts
See discussion here: https://github.com/ramda/types/issues/29
The current type definitions for `defaultTo` are incorrect in that the following test passes when it shouldn't:
```typescript
expectType<string | undefined>(R.defaultTo('default value', undefined)); // << incorrect
```
This PR updates the `defaultTo` type definitions such that the following tests pass:
```typescript
expectType<string>(defaultTo('default value', undefined));
expectType<string>(defaultTo(0, 'two'));
expectType<number>(defaultTo('zero', 2));
const numberOrUndefined = Math.random() < 0.5 ? 0 : undefined;
expectType<string | number>(defaultTo('default value', numberOrUndefined));
```
=> Updating defaultTo type definitions

types/isNotNil.d.ts
Use `NonNullable` so type guard is recognized as boolean by tools like [typescript-eslint/strict-boolean-expressions](https://typescript-eslint.io/rules/strict-boolean-expressions)
**Before**
**After**
=> Update: isNotNil use built-in NonNullable

test/map.test.ts, types/map.README.md, types/map.d.ts, types/util/tools.d.ts
This MR updates `map` to support mapping over an array, an object, or a Functor.
Caveat: due to typescript limitations, when passing `map(a)` into another function as a variable, typescript defaults to the last overload, this means that while the following works:
```typescript
map(toString)([1, 2, 3]); // ok
map(toString)({ a: 1, b: 2, c: 3 }); // ok
```
Passing to `pipe` only supports arrays
```typescript
pipe(map(toString))([1, 2, 3]); // ok
pipe(map(toString))({ a: 1, b: 2, c: 3 }); // error
```
I have a few ideas for how to fix the above caveat, and I will address it in a new issue
=> Update: Map

test/groupBy.test.ts, types/groupBy.d.ts
The grouping classifier function may have never returned one of the possible values, so there is not necessarily an array for each group.
Note: The test is sort of copied from DefinitelyTyped.
I noticed you seem to use `tsd expect*` functions in the other test, but wanted to avoid putting a huge `expectType` of sorts.
Testing this way seems like a pretty good idea here, because it's user-focused ('this expression with the groupBy result is allowed, this one is not').
Feel free to amend the test if you don't like that part.
=> fix(groupBy): return Partial Record

test/concat.test.ts, types/concat.d.ts
This update aligns the type def for `concat` to match the native `Array#concat()` method. Specifically to disallow concatenation of arrays of different types. That existing type def for `concat` was not typesafe and it should have never been that
It also improves the types for concat on strings a bit
=> Update: Concat

test/prop.test.ts, types/prop.d.ts
This update of the types for `prop` corrects what I consider a major flaw in the previous typing
The previous version used a utility type `Prop` that is defined in `util/tools.d.ts` What it essentially did was ignore unions with `undefined`, such that
```typescript
({ a: string } | undefined)['a'] // error
Prop<{ a: string } | undefined, 'a'> // string
```
This effectively side-steps the type safety that typescript gives us
Consider the following:
```typescript
type Todo = { description: string; isDone: boolean };
const todos: Todo[] = [/* ... */];
const firstActiveTodo = todo.find(todo => !todo.isDone);
//    ^? Todo | undefined
// the previous implementation of `prop` worked this way
const description = prop('description', firstActiveTodo);
//    ^? string
// the new implementation will …
```
=> Breaking: prop

types/remove.d.ts, types/reverse.d.ts, types/slice.d.ts, types/take.d.ts, types/transduce.d.ts, types/values.d.ts
Just some random fixes for things that were more general and could be dumped into a single PR
* Simplify the types for `values`
* Fix overload ordering for `slice`
* fix overload ordering for `reverse`
* fix placement of the generic for `placement`
* fix overload ordering for `take`
* fix overload ordering for `tranduce`
=> Fix: Random Fixes

test/anyPass.test.ts, test/both.test.ts, test/either.test.ts, test/ifElse.test.ts, types/allPass.d.ts, types/anyPass.d.ts, types/both.d.ts, types/either.d.ts, types/ifElse.d.ts, types/propEq.d.ts, types/util/tools.d.ts
Removing usage of `Pred` and`PredTypeguard`. Using inline definitions gives better error messages
```typescript
const gt10 = (x: number) => x > 10;
const lt20 = (x: number) => x < 20;
const isEmptyString = (x: string) => x === '';
both(gt10, isEmptyString); // type-error
// previous:
// Argument of type '(x: number) => boolean' is not assignable to parameter of type 'PredTypeguard<number, number>'
// ^^ This argument doesn't really tell you what is wrong, since the type `PredTypeguard` is hidden
// new:
// Argument of type '(x: number) => boolean' is not assignable to parameter of type '(a: number) => a is number'
// ^^ Using literals in the definition gives a more direct error message that's easier to understand
```
=> Fix: allPass, anyPass, both, either, ifElse 

test/fromPairs.test.ts, test/keys.test.ts, test/toPairs.test.ts, types/fromPairs.d.ts, types/keys.d.ts, types/toPairs.d.ts, types/toPairsIn.d.ts
Corrects the types for `keys`, `fromPairs`, `toPairs`, and `toPairsIn`
=> Update: keys related functions

types/type.d.ts
`R.type(async () => {});` returns `'AsyncFunction'`, which was not part of the return union
=> Update: add 'AsyncFunction' to return type union of `type`

test/pick.test.ts, types/pick.d.ts, types/util/tools.d.ts
Previous definition were not type-safe, playground explanation: https://tsplay.dev/wQJRjN
New definition strictly allows only a tuple of the keys for the obj it is picking from
=> Update: Pick

test/match.test.ts, types/match.d.ts
Correct typing for `match`, including currying
=> Update: match

test/prop.test.ts, types/prop.d.ts
The way `prop(key)(obj)` was typed was `obj extends Record<K, unknown>`. From typescript's point of view, this means that the object must contain the key, but not if the key was optional. The constraint that `prop(key)(obj)` should have is that if the key exists on `obj`, optional or not. To fix, `Partial<Record<K, unknown>>` should be used. But that's a lot of characters, `{ [P in K]?: unknown }` is the exact same thing with less characters, so going with that
=> Fix(prop): Allow optional props for prop(key)(obj) variety

test/pick.test.ts, types/pick.d.ts, types/util/tools.d.ts
Fixes: https://github.com/ramda/types/issues/76
The original typing for `pick` constrained the `names` array to have at least a length of 1 `[PropertyKey, ...PropertyKey[]]`. The reasoning behind this was to try and force the `names` to always be read as an array literal. The purpose was to directly return an object type with the specific values in `names` omited. This works well when you pass in an array literal or a typed tuple. However, that breaks down when you pass in a typed array.
```typescript
type Obj = { foo: string; bar: string; biz: string; baz: string };
// this worked fine because it was being read as an array literal
const r1 = pick(['foo', 'bar'], obj);
//    ^? { biz: string; baz: string }
const objKeys: (keyof Obj)[] = ['foo', 'bar'];
// this fails because `objKeys` has …
```
=> Fix(pick): Allow zero length array to be passed

package-lock.json, package.json, test/modifyPath.test.ts, types/modifyPath.d.ts
`modifyPath` now supports passing empty array in first arg, this update adds support for that
=> Update: support modifyPath change from 0.29.1

test/path.test.ts, types/path.d.ts
Was unintentionally removed in https://github.com/ramda/types/pull/66
=> fix(path): Put back in curried signature for path function

test/path.test.ts, types/path.d.ts
Fixing an incorrect typing update that happened here: https://github.com/ramda/types/pull/66/files#diff-4177c11b548623dcf1336a333250de80491ee007ea784f5afa933909181a9b20R69
That should have been `| undefined`, not `| unknown`
=> Fix: `path`

test/pluck.test.ts, types/pluck.d.ts
The current version of pluck typing has a big mistake: it always returns an array, when it should return an object if the object is passed as a parameter.
This commit can fix this.
=> fix(pluck): pluck now can return object

test/isNil.test.ts, test/isNotNil.test.ts, types/isNil.d.ts
Full explanation here: https://tsplay.dev/wXgXVW
=> fix(isNil): Accept generic type for inversion type extraction

test/omit.test.ts, test/pick.test.ts, types/omit.d.ts, types/pick.d.ts
typing `omit` same as `pick`
Additional fix for optional properties for `pick`
=> Update: omit

test/allPass.test.ts, test/anyPass.test.ts, test/propEq.test.ts, types/allPass.d.ts, types/anyPass.d.ts, types/propEq.d.ts
See this playground for full tests: https://tsplay.dev/mMlMdN
`propEq` needs a lot of updating. This MR is one of 3 towards that effort.
This first effort is just to update the typings to allow for a more correct range of typing when passing a `val` without yet knowing the type of `obj`
tl;dr is that when we know the type of `val` but not the type of `obj`, we're allowing for a wider type range for better support. These additions fix the following issues that the current typings don't support:
* val is `string` but the prob type is `string | number`
* prop type is `| null` (eg nullable)
* prop type is optional
The downside to these changes is that we lose errors when the types at `obj.prop` don't at all overlap with the type of `val`, but it will return `never` in those cases, which is …
=> Update: propEq to allow wider-typing for value in comparison

LICENSE.md
Copied verbatim from [ramda/ramda](https://github.com/ramda/ramda/blob/master/LICENSE.txt)
=> New: added LICENSE.md

test/allPass.test.ts, test/anyPass.test.ts, test/propEq.test.ts, types/allPass.d.ts, types/anyPass.d.ts, types/propEq.d.ts
Reverts ramda/types#74
@Nemo108 In my MR out on , this [comment](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68695/files#r1498384115) pointed out a test that I had [commented out](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68695/files#diff-a096ac4443ad8895567b9b66307ae20048ba4ff89d80098b646ef22fa1e47971R38-R40). I had the intention of coming back to, but forgot (human error).
That test is this:
```
const coll = [{ type: "BUY" }, { type: "SELL" }, { type: "BUY" }];
const isBuy = R.propEq("BUY", "type");
R.filter(isBuy, coll); // => [{ type: 'BUY' }, { type: 'BUY' }]
```
You get an error on `isBuy` being passed to `R.filter`:
<details>
<summary>Expand to see error</summary>
```
No overload matches this call.
Overload 1 of 5, '(pred: (val: { type: string; }) => val …
```
=> Revert "Update: propEq to allow wider-typing for value in comparison"

types/assoc.d.ts
Simplify typings on `assoc`
Turns out that overloading for the specific key/value scenarios is harder on typescript than returning a complex type checking via ternaries. This works better for pretty much all scenarios. Especially when passing results from curried `assoc` calls into other functions, eg `pipe(assoc('key', 'value'))` or `[].map(assoc('key', 'value'))`
See example here: https://tsplay.dev/Na5r0N
Fixes: https://github.com/ramda/types/issues/35
And: https://github.com/ramda/types/pull/37#issuecomment-1958615588
=> update(assoc) Simplify Typings to fix inference and cross function usage

test/filter.test.ts, test/reject.test.ts, types/filter.d.ts, types/reject.d.ts
Fixes https://github.com/ramda/types/issues/102
`list` should come after `dict`
=> fix(filter, reject) update overload orderings

package.json
I can't believe I fucked this up: https://github.com/ramda/types/pull/80/commits/8f80f42f2fd93ed5d3727a2d08b8e109289bd737#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519
While testing to see if this worked
```
"typesVersions": {
"<5": {
"index.d.ts": [
"ts4/index.d.ts"
],
"*": [
"ts4/*"
]
}
},
```
I was adding/removing it locally while testing it against a local repo with typescript@4. It worked as expected, and then, with it still removed, committed it 🤦
This will re-fix ts4 support
* Pull this repo: https://github.com/Harris-Miller/ramda-ts4-test and `npm ci`
* It's a simple project that uses the 2 ts@5 only functions `pick` and `omit`
* The project has ts@4 installed, so `npm run build` will have typescript errors
* Pull down this branch, `npm run build`
* Using …
=> Fix: ts4 support

types/type.d.ts
According to the [implementation](https://github.com/ramda/ramda/blob/master/source/type.js):
```ts
Object.prototype.toString.call(BigInt(123)).slice(8, -1) // "BigInt"
```
=> `type()` can return `BigInt`

test/forEach.test.ts, types/forEach.d.ts
Fixes https://github.com/ramda/types/issues/112
This makes the root `forEach` function go from 2 generics to 1 generic, which is breaking, but it can't be helped. The inference of an inline function is far more important. Besides, it's rare that anyone should have to set the generic manually.
=> fix(forEach) Remove forEach second generic on root function

test/zipObj.test.ts, types/util/zipObj.d.ts, types/zipObj.d.ts
Narrow values types per key when possible, otherwise fallback on wider mapped type.
Tests included
=> feat(zipObj): stricter types, add test

test/flow.test.ts, types/flow.d.ts
Types for https://github.com/ramda/ramda/pull/3441/
Todo:
=> new(flow) add types for new flow function
